import { StyleSheet } from "react-native";
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from "react-native-responsive-screen";
import { size } from "react-native-responsive-sizes";

export const coverBackgroundStyles = StyleSheet.create({
	backArrow: {
		position: 'absolute',
		top: size(5),
		left: size(18),
		backgroundColor: 'rgba(23,31,43,0.32)',
		borderRadius: size(18),
		padding: size(8),
		zIndex: 10,
		alignItems: 'center',
		justifyContent: 'center',
	},
	portraitContainer: {
		marginTop: 0,
		alignItems: "flex-start",
		justifyContent: "flex-end",
		width: "100%",
		paddingLeft: wp(2),
		zIndex: 2,
		flex: 1,
		position: "relative",
	},
	portrait: {
		width: wp(30),
		height: hp(25),
		aspectRatio: 0.7,
		borderRadius: wp(7),
		resizeMode: "cover",
		shadowColor: "#000",
		shadowOpacity: 0.18,
		shadowOffset: { width: 0, height: 4 },
		shadowRadius: 8,
		elevation: 6,
		borderWidth: 2,
		borderColor: "#2e3a5e",
		backgroundColor: "#263a4d",
		bottom: -hp(10),
	},
	container: {
		width: "100%",
		height: hp(35),
		overflow: "visible",
	},
	coverBg: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: hp(35),
		borderTopLeftRadius: size(24),
		borderTopRightRadius: size(24),
		resizeMode: 'cover',
		opacity: 0.45,
		zIndex: 0,
	},
	overlay: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: hp(35),
		borderTopLeftRadius: size(24),
		borderTopRightRadius: size(24),
		backgroundColor: 'rgba(23,31,43,0.18)',
		zIndex: 1,
	},
});
